# Generated by Django 5.0.6 on 2024-06-15 15:06

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='product_ordered')),
                ('quantity', models.IntegerField(verbose_name='number_of_order')),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='total_price')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_time')),
            ],
        ),
    ]
