# Generated by Django 5.0.6 on 2024-06-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True, verbose_name='total_price'),
        ),
    ]
